### ISSUE TITLE
Unable to download the latest release: "Failed - Download error"

### ISSUE THREAD

**Issue by mickael28** [Olstyle/SoftThConfigTool#1]
Hi, 

I was trying to download the latest release by clicking on [http://www.mechatronics4you.com/wp-content/plugins/download-monitor/download.php?id=13](http://www.mechatronics4you.com/wp-content/plugins/download-monitor/download.php?id=13) but I keep on getting 'Failed - Download error'

I'm using Windows 10 and I think the antivirus is detecting it as a virus or similar and deleting it before I can access it. Do you know why this could be? And can you think of any workaround to be able to download it and execute it?

Thanks!

**Comment by Olstyle** [comment]
I can confirm that Windows Defender is calling the exe a virus. This has nothing to do with the download procedure but with some kind of heuristic inside Defender. 
I have build it again in VS 2012, lets see how that works out
[SoftTh Config Tool.zip](https://github.com/Olstyle/SoftThConfigTool/files/739865/SoftTh.Config.Tool.zip)
